name: Debian packaging

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #   - name: Get tag name
    #     id: get_tag_name
    #     run:  echo :: set-output name=VERSION:${GITHUB_REF/refs\/tags\//}
    #   ref: ${{ steps.get_tag_name.outputs.VERSION }}
      - uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.ref }}

      - name: Install packaged dependencies
        run: .github/install_dependencies

      - name: Configure
        run: |
            cmake -B ${{github.workspace}}/build_Release_NFM -DCMAKE_BUILD_TYPE=Release -DNFM=TRUE -DBUILD_UNITTESTS=TRUE

      - name: Build
        run: |
            VERBOSE=1 cmake --build ${{github.workspace}}/build_Release_NFM -j

      - name: create sample script
        run: |
            ls -la
            git status
            mkdir -p .debpkg/usr/bin
            cmake --install ${{github.workspace}}/build_Release_NFM --prefix .debpkg/usr/bin
            ls -la .debpkg/usr/bin
            #chmod +x .debpkg/usr/bin/rtl_airband

            # create DEBIAN directory if you want to add other pre/post scripts
            mkdir -p .debpkg/DEBIAN
            echo -e "echo postinst" > .debpkg/DEBIAN/postinst
            chmod +x .debpkg/DEBIAN/postinst

      - uses: jiro4989/build-deb-action@v2
        with:
            package: rtlsdt-airband
            package_root: .debpkg
            maintainer: charlie-foxtrot
            version: ${{ github.ref }} # refs/tags/v*.*.*
            arch: 'amd64'
            depends: 'libc6 (>= 2.28)' # since Debian Buster
            desc: 'RTLSDR Airband - A multiband decoder for AM and NFM signals'
            compress_type: xz
