name: Debian packaging

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packaged dependencies
        run: .github/install_dependencies

      - name: Configure
        run: |
            cmake -B ${{github.workspace}}/build_Release_NFM -DCMAKE_BUILD_TYPE=Release -DNFM=TRUE

      - name: Build
        run: |
            VERBOSE=1 cmake --build ${{github.workspace}}/build_Release_NFM -j

      - name: create .deb content structure
        run: |
            mkdir -p .debpkg/DEBIAN
            # echo -e "echo postinst" > .debpkg/DEBIAN/postinst
            # chmod +x .debpkg/DEBIAN/postinst
            # systemd services
            mkdir -p .debpkg/lib/systemd/system/
            sed 's|/usr/local/bin/rtl_airband|/usr/bin/rtlsdr_airband|g' init.d/rtl_airband.service > .debpkg/lib/systemd/system/rtlsdr_airband.service
            #
            mkdir -p .debpkg/usr/bin
            cp ${{github.workspace}}/build_Release_NFM/src/rtl_airband .debpkg/usr/bin/rtlsdr_airband
            pushd .debpkg/usr/bin
            ln -s rtlsdr_airband rtl_airband
            popd
# TODO add
# default configuration under /etc
# example configuration under /usr/share/docs/ maybe?
      - uses: jiro4989/build-deb-action@v3
        with:
            package: rtlsdr-airband
            package_root: .debpkg
            maintainer: charlie-foxtrot
            version: ${{ github.ref }} # refs/tags/v*.*.*
            arch: 'amd64'
            depends: 'libconfig++9v5 (>= 1.5-0.4), libmp3lame0 (>= 3.100), libshout3 (>= 2.4.5), librtlsdr0 (>= 0.6.0), libsoapysdr0.8 (>= 0.8.1), libfftw3-single3 (>= 3.3.8), libpulse0 (>= 14.2)'
            desc: 'RTLSDR Airband - A multiband decoder for AM and NFM signals'
            compress_type: xz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: rtlsdr-airband_*_amd64.deb
          fail_on_unmatched_files: true
            
