name: Debian packaging

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packaged dependencies
        run: .github/install_dependencies

      - name: Configure
        run: |
            cmake -B ${{github.workspace}}/build_Release_NFM -DCMAKE_BUILD_TYPE=Release -DNFM=TRUE

      - name: Build
        run: |
            VERBOSE=1 cmake --build ${{github.workspace}}/build_Release_NFM -j

      - name: create .deb content structure
        run: |
            mkdir -p .debpkg/DEBIAN
            mkdir -p .debpkg/usr/bin
            # echo -e "echo postinst" > .debpkg/DEBIAN/postinst
            # chmod +x .debpkg/DEBIAN/postinst
            cp ${{github.workspace}}/build_Release_NFM/src/rtl_airband .debpkg/usr/bin
            sudo chown -R root:root .debpkg/

      - uses: jiro4989/build-deb-action@v2
        with:
            package: rtlsdr-airband
            package_root: .debpkg
            maintainer: charlie-foxtrot
            version: ${{ github.ref }} # refs/tags/v*.*.*
            arch: 'amd64'
            depends: 'libconfig++9v5, libmp3lame0, libshout3, librtlsdr0, libsoapysdr0.8, libfftw3-single3, libpulse0'
            desc: 'RTLSDR Airband - A multiband decoder for AM and NFM signals'
            compress_type: xz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: rtlsdr-airband_*_amd64.deb
          fail_on_unmatched_files: true
            
