name: Debian packaging

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packaged dependencies
        run: .github/install_dependencies

      - name: Configure
        run: |
            cmake -B ${{github.workspace}}/build_Release_NFM -DCMAKE_BUILD_TYPE=Release -DNFM=TRUE

      - name: Build
        run: |
            VERBOSE=1 cmake --build ${{github.workspace}}/build_Release_NFM -j

      - name: create sample script
        run: |
            mkdir -p .debpkg/usr/bin
            cp ${{github.workspace}}/build_Release_NFM/src/rtl_airband .debpkg/usr/bin
            mkdir -p .debpkg/DEBIAN
            echo -e "echo postinst" > .debpkg/DEBIAN/postinst
            chmod +x .debpkg/DEBIAN/postinst
            sudo chown -R root:root .debpkg/
            ls -laR .debpkg/

      - uses: jiro4989/build-deb-action@v2
        with:
            package: rtlsdt-airband
            package_root: .debpkg
            maintainer: charlie-foxtrot
            version: ${{ github.ref }} # refs/tags/v*.*.*
            arch: 'amd64'
            depends: 'libc6 (>= 2.28)' # since Debian Buster
            desc: 'RTLSDR Airband - A multiband decoder for AM and NFM signals'
            compress_type: xz

      - name: list package content
        run: |
          ls -la rtlsdt-airband*.deb
          dpkg-deb --info rtlsdt-airband*.deb
          dpkg-deb --raw-extract rtlsdt-airband*.deb /tmp
          ls -laR /tmp
